# Generated by Django 4.1.3 on 2022-11-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="published",
            new_name="publish",
        ),
    ]
