# Generated by Django 4.1.3 on 2022-11-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_published_product_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=200, unique_for_date="publish"),
        ),
    ]
