# Generated by Django 4.1.3 on 2022-11-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="catalog.product",
                    ),
                ),
                (
                    "declared_unit",
                    models.CharField(
                        choices=[
                            ("m", "meter"),
                            ("m3", "m3"),
                            ("m2", "m2"),
                            ("kg", "kg"),
                            ("piece", "piece"),
                        ],
                        default="m2",
                        max_length=64,
                        null=True,
                        verbose_name="Declared unit",
                    ),
                ),
                (
                    "total_co2e_kg_mf",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Total CO2e [kg]"
                    ),
                ),
                (
                    "total_biogenic_co2e",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Total Biogenic CO2e [kg]"
                    ),
                ),
                (
                    "carbon_sorting",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Carbon Sorting"
                    ),
                ),
                (
                    "water_use_kg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Water Use [kg]"
                    ),
                ),
                (
                    "use_and_maintenance",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Use & Maintenance (B1-B5) [kg]",
                    ),
                ),
                (
                    "end_of_life",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="End of Life excluding transport (C1, C3, C4) [kg]",
                    ),
                ),
                (
                    "recycled_content",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Recycled Content [%]"
                    ),
                ),
                (
                    "recyclable_content",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Recyclable Content [%]"
                    ),
                ),
                (
                    "reuse_potential",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Re-use Potential [%]"
                    ),
                ),
                ("odp", models.FloatField(blank=True, null=True, verbose_name="ODP")),
                (
                    "manufacturing",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Manufacturing (A1-A3) [kg]"
                    ),
                ),
                (
                    "on_site_installation",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="On-site Installation (A5) [kg]",
                    ),
                ),
                (
                    "energy_recovery_possibility",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Energy Recovery Possibility [%]",
                    ),
                ),
            ],
            options={
                "ordering": ("product",),
            },
        ),
    ]
