# Generated by Django 4.1.3 on 2022-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, max_length=255, upload_to="products/"),
        ),
    ]
