# Generated by Django 4.1.3 on 2022-11-25 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0009_alter_product_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": [django.db.models.functions.text.Lower("name")]},
        ),
        migrations.AddField(
            model_name="product",
            name="users",
            field=models.ManyToManyField(
                related_name="products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
